/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EventEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_STAKE"
      | "REFUND_CUTOFF"
      | "emergencyWithdraw"
      | "forfeit"
      | "getStake"
      | "hasActiveStake"
      | "hashEventId"
      | "owner"
      | "refund"
      | "release"
      | "stake"
      | "stakes"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Forfeited" | "Refunded" | "Released" | "Staked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REFUND_CUTOFF",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forfeit",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStake",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveStake",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "hashEventId", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REFUND_CUTOFF",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "forfeit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashEventId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ForfeitedEvent {
  export type InputTuple = [
    eventId: BytesLike,
    attendee: AddressLike,
    organizer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    eventId: string,
    attendee: string,
    organizer: string,
    amount: bigint
  ];
  export interface OutputObject {
    eventId: string;
    attendee: string;
    organizer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    eventId: BytesLike,
    attendee: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [eventId: string, attendee: string, amount: bigint];
  export interface OutputObject {
    eventId: string;
    attendee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [
    eventId: BytesLike,
    attendee: AddressLike,
    organizer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    eventId: string,
    attendee: string,
    organizer: string,
    amount: bigint
  ];
  export interface OutputObject {
    eventId: string;
    attendee: string;
    organizer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    eventId: BytesLike,
    attendee: AddressLike,
    organizer: AddressLike,
    amount: BigNumberish,
    eventStartTime: BigNumberish
  ];
  export type OutputTuple = [
    eventId: string,
    attendee: string,
    organizer: string,
    amount: bigint,
    eventStartTime: bigint
  ];
  export interface OutputObject {
    eventId: string;
    attendee: string;
    organizer: string;
    amount: bigint;
    eventStartTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): EventEscrow;
  waitForDeployment(): Promise<this>;

  interface: EventEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  REFUND_CUTOFF: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  forfeit: TypedContractMethod<
    [eventId: BytesLike, attendee: AddressLike],
    [void],
    "nonpayable"
  >;

  getStake: TypedContractMethod<
    [eventId: BytesLike, attendee: AddressLike],
    [
      [bigint, string, bigint, bigint, bigint] & {
        amount: bigint;
        organizer: string;
        status: bigint;
        stakedAt: bigint;
        eventStartTime: bigint;
      }
    ],
    "view"
  >;

  hasActiveStake: TypedContractMethod<
    [eventId: BytesLike, attendee: AddressLike],
    [boolean],
    "view"
  >;

  hashEventId: TypedContractMethod<[eventId: string], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[eventId: BytesLike], [void], "nonpayable">;

  release: TypedContractMethod<
    [eventId: BytesLike, attendee: AddressLike],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<
    [eventId: BytesLike, organizer: AddressLike, eventStartTime: BigNumberish],
    [void],
    "payable"
  >;

  stakes: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        amount: bigint;
        attendee: string;
        organizer: string;
        status: bigint;
        stakedAt: bigint;
        eventStartTime: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFUND_CUTOFF"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "forfeit"
  ): TypedContractMethod<
    [eventId: BytesLike, attendee: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getStake"
  ): TypedContractMethod<
    [eventId: BytesLike, attendee: AddressLike],
    [
      [bigint, string, bigint, bigint, bigint] & {
        amount: bigint;
        organizer: string;
        status: bigint;
        stakedAt: bigint;
        eventStartTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasActiveStake"
  ): TypedContractMethod<
    [eventId: BytesLike, attendee: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashEventId"
  ): TypedContractMethod<[eventId: string], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[eventId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<
    [eventId: BytesLike, attendee: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [eventId: BytesLike, organizer: AddressLike, eventStartTime: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        amount: bigint;
        attendee: string;
        organizer: string;
        status: bigint;
        stakedAt: bigint;
        eventStartTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Forfeited"
  ): TypedContractEvent<
    ForfeitedEvent.InputTuple,
    ForfeitedEvent.OutputTuple,
    ForfeitedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;

  filters: {
    "Forfeited(bytes32,address,address,uint256)": TypedContractEvent<
      ForfeitedEvent.InputTuple,
      ForfeitedEvent.OutputTuple,
      ForfeitedEvent.OutputObject
    >;
    Forfeited: TypedContractEvent<
      ForfeitedEvent.InputTuple,
      ForfeitedEvent.OutputTuple,
      ForfeitedEvent.OutputObject
    >;

    "Refunded(bytes32,address,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "Released(bytes32,address,address,uint256)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;

    "Staked(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
  };
}
